export default {
  primary: '#2296EE',
  'primary-content': '#FFFFFF',
  secondary: '#F000B8',
  'secondary-content': '#FFFFFF',
  accent: '#37CDBE',
  neutral: '#ffffff',
  'base-100': '#FFFFFF',
  'base-200': '#fafafa',
  info: '#3ABFF8',
  success: '#36D399',
  warning: '#FBBD23',
  error: '#F87272',
  '--rounded-box': '0.5rem',
  '--rounded-btn': '0.25rem',
}
